###
get http://localhost:3000/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmF2aSIsImlhdCI6MTcyNTYzMTI1MiwiZXhwIjoxNzI1NjMxMjcyfQ.ScSTktyGNhhnJoxU0ubIL5O7_e_hZkyHDnsPqAKlEmI
###
post http://localhost:3000/user/register
Content-Type: application/json

{
    "name":"Ravi",
    "age":21,
    "email":"ravi@gmail.com",
    "password":"ravi123",
    "role":"merchant",
    "address":{
        "city":"Vij",
        "state":"AP"
    }
}
###
post http://localhost:3000/user/login
Content-Type: application/json

{
    "nameUrl":"Ravi",
    "password":"ravi123"
}

###
put http://localhost:3000/user/update
Content-Type: application/json

{
    "nameUrl":"Ravi",
    "age":21,
    "email":"ravi@gmail.com",
    "password":"$2b$10$vg91Ag4KW84AVAn8pe3q0e4Fi9PIc62Xy7TV3DodRXnMs3Z5wLvIe",
    "role":"merchant",
    "address":{
        "city":"Kphb",
        "state":"Hyd"
    }
}
###
delete http://localhost:3000/user/delete/Ravi