###
get http://localhost:3000/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVXNlcjEiLCJpYXQiOjE3MjYzMDkzODEsImV4cCI6MTcyNjM0NTM4MX0.VwzU69QZLmKO5DUJt64e1XJzcKsKziX7stjdqkEUZys

###
get http://localhost:3000/user/Ravi
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVXNlcjEiLCJpYXQiOjE3MjYzMDkzODEsImV4cCI6MTcyNjM0NTM4MX0.VwzU69QZLmKO5DUJt64e1XJzcKsKziX7stjdqkEUZys

###
post http://localhost:3000/user/register
Content-Type: application/json

{
    "name":"Ravi",
    "age":21,
    "email":"ravi@gmail.com",
    "password":"ravi123",
    "role":"merchant",
    "address":{
        "city":"Vij",
        "state":"AP"
    }
}

###
post http://localhost:3000/user/login
Content-Type: application/json

{
    "nameUrl":"User1",
    "password":"password123"
}

###
put http://localhost:3000/user/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVXNlcjEiLCJpYXQiOjE3MjYzMDkzODEsImV4cCI6MTcyNjM0NTM4MX0.VwzU69QZLmKO5DUJt64e1XJzcKsKziX7stjdqkEUZys
Content-Type: application/json

{
    "nameUrl":"Ravi",
    "age":21,
    "email":"ravi@gmail.com",
    "password":"$2b$10$vg91Ag4KW84AVAn8pe3q0e4Fi9PIc62Xy7TV3DodRXnMs3Z5wLvIe",
    "role":"merchant",
    "address":{
        "city":"Kphb",
        "state":"Hyd"
    }
}

###
delete http://localhost:3000/user/delete/Ravi
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVXNlcjEiLCJpYXQiOjE3MjYzMDkzODEsImV4cCI6MTcyNjM0NTM4MX0.VwzU69QZLmKO5DUJt64e1XJzcKsKziX7stjdqkEUZys

###
post http://localhost:3000/user/filter
Content-Type: application/json

{
    "filters":[
        {
            "field" : "address.city",
            "value" : "Kphb"
        }
    ]
}